sudo: false
language: node_js
node_js:
- node
- lts/*
- '10'
jobs:
  include:
  - stage: npm release
    node_js: node
    script: echo "Deploying to npm ..."
    deploy:
      provider: npm
      email:
        secure: KKkUPRG+L3vb9alIgo106OXzWRE9RL0rsMe9Rcu0LYpxOZRaahhfSHf1SZU29FjchxZdij0X1q+v+FCfcPa+NHOha7KAJ0RFw/dtXy/jS/Jml9jXGegbHX9OIEeHslT7sUf+JBs8jn81lAA4rABMhWqmLriqxFxmB1jB5CZ8CnV/xh4BtxrjukrdFHz4gIhDFtoLwRy8bzNuinl6qyMaLc2E6gc6qj8/ufMfRZABtxChXt+yLioVsIkc7tCmCytjSydft6ecNNfVZileBiOuMG1fxX/CJ1SxJhDcxhoWDBdCAvwABA9ydYhlBkA2p6vWglvAJH+PwEftoaP2XfvIVolVFdtqbQ3JyIjxsHaQnMh+Q6ricyBoLMrwlZXOecnPl3rq+DNXNFqxVvaiyvcMvzL27BJcSgQj0iUuCDUiK2QFZ1VXjcGh0vg6BNbQIi6L1pm99DRodEIHrVmxF5IJKzVeb/5JJvqUClGf76l8rVH4mvMbr6rqleUawFq7wkLJmd+Inm+HsoHXRklVuMyX/9HeDTSWe1yKEBGndwT89P4rwOZwd78D/sIQZTq/snblhkKcqC+o799MRo80azznRWMpG23eoCS/rsg2hobdPtiQLZRFoTVcs+qV93/xIwGNcCE6M+IKNqKINOtc5KExeVzBUevSaRPeZN1EXA0MDS4=
      api_key:
        secure: ovCrqIuxu4AQJfUDs2KPJVb5k8NzWfWwIUectgMduSirYKfMP4ZGIkRgbgEpiIJG1VSTgMyeOkuhNDMnLjXFEhx/1QcpZDG2InMWJ9UNLPNIaE7CFwcAjnn0faXSFcEsVSZjh1ti+/u0si65qXpt6sVvnssbIK1ch4ZpW7XrhWXGG0HbFpnFrcgnyOem2fNbW0hnXbZTQXVYbjJ+vKg8zczPM6JZbGOoGwyF92VxiKLJhJQ40GaH5qgQUaeoNRfi/yJq3jz1Ni5YZeFZyUK7JGQJC25B7fFrzCuuMrqLKe2FqE68DpU9ESY1cE3JUChjWiYao4Cn0HGSC0tcyq0d6vTO2rTiWp1/xwmcyfBQxQJ1lbl25R7pFdBobgaKTTJ1egWMl16gAQiQ9W+5h5nOdgLPz55GLHZCe99H4uiSbK6hld644o0NUb921cwst5tzTs6M/gezq65HJmQv6E7VD3SnWpv59iJfWGMnoPukLSJsGZPkw9DKDUyOIDn4TnsI4+irnljnlFMV6KM5NDOSqopwEteTOGoXtm8K2Os21M2uek/VXH/neGc2Mdwguzr0aNcXck5HzHWz4G15LQ8hCLK23R7oBsl5Tba2/0ZMKQJY0p17deTSo8/4HJcqpvZ1pQL9v2T5DvBKk6CRJ+p2a0S+erJctCiZfjzS0Bp4H0g=
      on:
        tags: true
        node: node
